#!/bin/bash

YELLOW='\033[1;33m'
NC='\033[0m' # No Color

last_word=$(echo "$1" | rev | cut -d' ' -f1 | rev)

if [ "$last_word" = "--full" ]; then
    echo "Installing brew dependencies.."    
    brew bundle install
    echo "Installing app dependencies..."
    pnpm install > /dev/null 2>&1
     colima start --vm-type vz      
    # SET ENV VARIBLE DID_VM_MOUNT = TRUE             
    docker build -t film-backend .    
    colima stop  

     printf "\n✨Setup Finished. You can now run engine up\n"
#     echo "Setup Installed, Verifying environment files"

#         cd apps/mongo-node

#         if [ -f .env ]; then
#             echo "[Mongo-Node]: .env file found, skipping..."
#               printf "\n✨Setup Finished. You can now run take super✨\n"
#         else
#             touch .env

#             #  create a process that grabs mongo url
#   echo -e "${YELLOW}[mongo]: It looks like you are missing the Mongo connection URL. 
#         This URL is like a special address that allows your Mongo-node server to find and communicate with your Mongo database. 
#         Here's what you need to do:${NC}

#         Grab your Mongo connection URL. It should look something like this: 
#         mongodb+srv://<username>:<password>@<hostname>:<port>/<databasename>?retryWrites=true&w=majority"

#     read -p "Enter the Mongo connection URL: " response
#       echo "DATABASE_URL='${response}'" >> .env
#             echo "PORT='6001'" >> .env
#             echo "[Mongo-Node]: Created env file"
#             printf "\n✨Setup Finished. You can now run take super✨\n"
#         fi
else
    echo -e "${YELLOW}Skipping Brew dependencies installation (use --full, if needed). ${NC}"
    echo -e "${YELLOW}Skipping env verification (use --full, if needed).${NC}"
    echo "Installing app dependencies..."
    # pnpm install > /dev/null 2>&1
    pwd
    cd apps/backend
    colima start --vm-type vz      
    # SET ENV VARIBLE DID_VM_MOUNT = TRUE             
    docker build -t film-backend .    
    colima stop  

#  SET ENV VARIBLE IS_DOCKER_BUILD = TRUE

    printf "\n✨Setup Finished. You can now run engine up\n"

fi

