#!/bin/bash

# Define a cleanup function
cleanup() {
   # colima stop
   echo 'Engine powered down, service stopped!'
}

# Set the trap to call the cleanup function on script exit (EXIT), interrupt (INT), or termination (TERM)
trap cleanup EXIT INT TERM

cd apps/backend
docker compose up