version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ''
  app:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    image: film/backend:local
    ports:
      - '8080:8080'
