version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./dockerdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: film
  app:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    image: film/backend:local
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: film
