import { Response } from 'express';
import { adminStorage } from '../firebaseAdmin';
import {
  Collection,
  CollectionFormData,
  CollectionType,
  FirebasePhotoMetadata,
} from '@film/photos-iso';
import {
  doc,
  updateDoc,
  collection,
  query,
  where,
  getDocs,
  getDoc,
} from 'firebase/firestore';
import { db } from '../db';

export async function getFilesandMeta() {
  const [files] = await adminStorage.getFiles();

  const filePromises = files.map(async (file) => {
    const [url] = await file.getSignedUrl({
      action: 'read',
      expires: '03-17-2025',
    });

    const [metadata] = await file.getMetadata();

    const processedMetadata = {
      ...metadata.metadata,
      name: file.name, // Adding the file name to the metadata
      home_display: metadata.metadata?.home_display === 'true',
      // @ts-ignore
      collection: metadata.metadata?.collection?.includes(',')
        ? metadata.metadata.collection
            // @ts-ignore

            .split(',')
            // @ts-ignore

            .map((item) => item.trim().replace(/[\[\]]/g, ''))
        : // @ts-ignore

          metadata.metadata?.collection?.replace(/[\[\]]/g, ''),
    };

    return { url, metadata: processedMetadata };
  });

  const photos = await Promise.all(filePromises);

  return photos;
}

// Function to get the file reference from the URL
export function getFileFromUrl(url: string) {
  // Remove the base URL and extract the file path
  const filePath = decodeURIComponent(
    // @ts-ignore

    url.split('/').slice(-1)[0].split('?')[0]
  );
  const file = adminStorage.file(filePath);
  return file;
}

export async function updatePicMetadata(
  res: Response,
  url: string,
  collection: string,
  oldMeta: FirebasePhotoMetadata,
  current: string,
  removeFromCollection: boolean
) {
  const filePath = decodeURIComponent(
    //  @ts-ignore
    url.split('/').slice(-1)[0].split('?')[0]
  );

  const file = adminStorage.file(filePath);

  if (removeFromCollection) {
    if (typeof oldMeta.collection === 'string') {
      oldMeta.collection = collection;
    } else if (Array.isArray(oldMeta.collection)) {
      // If it's an array, push the new collection
      oldMeta.collection.push(collection);
      oldMeta.collection = oldMeta.collection.filter(
        (item) => item !== current
      );
    }
  }

  if (!removeFromCollection) {
    if (typeof oldMeta.collection === 'string') {
      oldMeta.collection = [current, collection];
    } else if (Array.isArray(oldMeta.collection)) {
      // If it's an array, push the new collection
      oldMeta.collection.push(collection);
    }
  }

  // Define the new metadata you want to set
  const newMetadata = {
    home_display: oldMeta.home_display, // Example: Update this field as needed
    collection: oldMeta.collection, // Example: Update this field as needed
  };

  try {
    // Update the file metadata
    const updatedMetadata = file.setMetadata({
      // @ts-ignore
      metadata: newMetadata,
    });

    console.log('Metadata updated successfully:', updatedMetadata);
    return { metadata: updatedMetadata };
  } catch (error) {
    console.error('Error updating metadata:', error);
  }
}

// * This function utilizes two distinct types of references:
//     * **`ref`:** This refers to a custom property within your component, likely used to specify a particular collection.
//     * **`docRef`:** This represents a reference to a Firestore collection, generated by the Firestore library itself.
export async function updateCollectionCoverUrl(
  ref: CollectionType,
  signedUrl: string
) {
  const collectionsRef = collection(db, 'collection');
  const q = query(collectionsRef, where('ref', '==', ref));

  const snapshot = await getDocs(q);

  if (snapshot.empty) {
    throw new Error('No collection found');
  }
  const docRef = snapshot.docs[0]!.ref;

  await updateDoc(docRef, { cover_image: signedUrl });
}

export async function updateCollectionFields(
  ref: CollectionType,
  updateFields: Partial<CollectionFormData> // Use Partial<CollectionFormData> to accept dynamic updates
) {
  const collectionsRef = collection(db, 'collection');
  const q = query(collectionsRef, where('ref', '==', ref));

  const snapshot = await getDocs(q);

  if (snapshot.empty) {
    throw new Error('No collection found');
  }

  const docRef = snapshot.docs[0]!.ref;

  // Handle the specific case for updating color map fields
  if (updateFields.shadow_color || updateFields.text_color) {
    // If either shadow_color or text_color is included, we need to update the color map
    const currentDoc = (await getDoc(docRef)).data();

    const colorMap = currentDoc?.colors || {}; // Safely access the current color map

    // Update the color map with the provided values
    if (updateFields.shadow_color) {
      colorMap.shadowColor = updateFields.shadow_color;
    }

    if (updateFields.text_color) {
      colorMap.textColor = updateFields.text_color;
    }

    // Update the document with the new color map
    await updateDoc(docRef, {
      colors: colorMap, // Update the colors field with the updated color map
      ...updateFields, // Spread the other fields that are not related to colors
    });
  } else {
    // For all other fields, just update directly
    await updateDoc(docRef, updateFields);
  }
}
