INSERT INTO photos.photo (image_url, collection, home_display)
VALUES 
  ('https://doron-photo-app.s3.amazonaws.com/eight.jpeg', 'howard', true),
  ('https://doron-photo-app.s3.amazonaws.com/five.jpeg', 'howard', true),
  ('https://doron-photo-app.s3.amazonaws.com/thirteen.jpeg', 'howard', true),
  ('https://doron-photo-app.s3.amazonaws.com/thirtythree.jpeg', 'howard', false),
  ('https://doron-photo-app.s3.amazonaws.com/tweleve.jpeg', 'howard', true),
  ('https://doron-photo-app.s3.amazonaws.com/thirtytwo.jpeg', 'howard', false),
  ('https://doron-photo-app.s3.amazonaws.com/two.jpeg', 'howard', true),
  ('https://doron-photo-app.s3.amazonaws.com/fifthteen.jpeg', 'NYC', true),
  ('https://doron-photo-app.s3.amazonaws.com/fourteen.jpeg', 'NYC', true),
  ('https://doron-photo-app.s3.amazonaws.com/seven.jpeg', 'NYC', true ),
  ('https://doron-photo-app.s3.amazonaws.com/six.jpeg', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/ten.jpeg', 'NYC', true),
  ('https://doron-photo-app.s3.amazonaws.com/thirty.jpeg', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/thirtyFive.JPG', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/thirtyfour.JPG', 'NYC', true),
  ('https://doron-photo-app.s3.amazonaws.com/thirtySeven.JPG', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/thirtySix.JPG', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/three.jpeg', 'NYC', true),
  ('https://doron-photo-app.s3.amazonaws.com/twentyfour.jpeg', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/twentyfive.jpeg', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/twentynine.jpeg', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/twentyeight.JPG', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/twentyseven.jpg', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/twentysix.jpg', 'NYC', true),
  ('https://doron-photo-app.s3.amazonaws.com/twentytwo.jpeg', 'NYC', false),
  ('https://doron-photo-app.s3.amazonaws.com/eighteen.jpg', 'grenada',true ),
  ('https://doron-photo-app.s3.amazonaws.com/twenty.JPG', 'grenada',true ),
  ('https://doron-photo-app.s3.amazonaws.com/eleven.jpeg', 'landmarks',false ),
  ('https://doron-photo-app.s3.amazonaws.com/twentythree.jpeg', 'landmarks', false),
  ('https://doron-photo-app.s3.amazonaws.com/four.jpeg', 'qt', true),
  ('https://doron-photo-app.s3.amazonaws.com/nineteen.jpg', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/one.jpeg', 'qt', true),
  ('https://doron-photo-app.s3.amazonaws.com/seventeen.JPG', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/sixthteen.jpeg', 'qt', true),
  ('https://doron-photo-app.s3.amazonaws.com/twentyone.jpg', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/quicktripsPics/oneQT.JPG', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/quicktripsPics/three.JPG', 'qt', false), 
  ('https://doron-photo-app.s3.amazonaws.com/quicktripsPics/two.JPG', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/quicktripsPics/six.JPG', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/quicktripsPics/eight.JPG', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/quicktripsPics/five.JPG', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/quicktripsPics/fourQT.JPG', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/quicktripsPics/94F8F1D1-3537-419D-8341-9BE4D25E4058_1_201_a.jpeg', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/quicktripsPics/seven.JPG', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/quicktripsPics/nine.JPG', 'qt', false),
  ('https://doron-photo-app.s3.amazonaws.com/landmarksPics/three.JPG', 'landmarks', false), 
  ('https://doron-photo-app.s3.amazonaws.com/landmarksPics/two.JPG', 'landmarks', false),
  ('https://doron-photo-app.s3.amazonaws.com/landmarksPics/two.JPG', 'landmarks', false),
  ('https://doron-photo-app.s3.amazonaws.com/grenadaPics/k.JPG', 'grenada', false),
  ('https://doron-photo-app.s3.amazonaws.com/grenadaPics/j.JPG', 'grenada', false),
  ('https://doron-photo-app.s3.amazonaws.com/grenadaPics/h.JPG', 'grenada', false),
  ('https://doron-photo-app.s3.amazonaws.com/grenadaPics/i.JPG', 'grenada', false);
  




