
                -- Auto-generated by an admin
 -- Migration edit-collection action on table photos.collection

                UPDATE photos.collection
            SET colors = '{"textColor":"fxdzs","shadowColor":"fxd"}', name = 'Landmarks ', description = 'vz', display_name = 'gfds'
                WHERE id = 'collection-4';