
                -- Auto-generated by an admin
 -- Migration edit-collection action on table photos.collection

                UPDATE photos.collection
            SET colors = '{"textColor":"fds","shadowColor":"fds"}', name = 'gfvdzs', description = 'fvdcsxa', display_name = 'dfs'
                WHERE id = 'collection-4';